name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    permissions:
      contents: write
    uses: dcc-bigfred/common/.github/workflows/rust-release.yml@v2
    with:
      elf_binaries: wireless-programmer-linux-arm64,wireless-programmer-linux-amd64
      elf_section: .wireless-programmer.version
      ci_workflow: ci.yml
    secrets: inherit
